= Cyface Android Utils Library

image:https://github.com/cyface-de/android-utils/workflows/Gradle%20Build/badge.svg[link="https://github.com/cyface-de/android-utils/actions"]
image:https://github.com/cyface-de/android-utils/workflows/Gradle%20Publish/badge.svg[link="https://github.com/cyface-de/android-utils/actions"]

This project contains the Cyface Android Utils Library which contains
methods and classes used by multiple Cyface Libraries. This separation
is required to avoid circular dependencies.

* <<integration-guide,Integration Guide>>
* <<developer-guide,Developer Guide>>
* <<license,License>>

[[integration-guide]]
== Integration Guide

This library is published to the Github Package Registry.

To use it as a dependency in your app you need to:

. Make sure you are authenticated to the repository:
 ** You need a Github account with read-access to this Github repository
 ** Create a https://github.com/settings/tokens[personal access token on Github] with "read:packages" permissions
 ** Create or adjust a `local.properties` file in the project root containing:

+
....
github.user=YOUR_USERNAME
github.token=YOUR_ACCESS_TOKEN
....
** Add the custom repository to your `build.gradle`:

+
....
def properties = new Properties()
properties.load(new FileInputStream("local.properties"))

repositories {
    // Other maven repositories, e.g.:
    google()
    mavenCentral()
    gradlePluginPortal()
    // Repository for this library
    maven {
        url = uri("https://maven.pkg.github.com/cyface-de/android-utils")
        credentials {
            username = properties.getProperty("github.user")
            password = properties.getProperty("github.token")
        }
    }
}
....
. Add this package as a dependency to your app's `build.gradle`:
+
....
dependencies {
    implementation "de.cyface:android-utils:$utilsVersion"
}
....

. Set the `$utilsVersion` gradle variable to the https://github.com/cyface-de/android-utils/releases[latest version].

[[developer-guide]]
== Developer Guide

This section is only relevant for developers of this library.

[[release-a-new-version]]
=== Release a new version

See https://github.com/cyface-de/android-backend#release-a-new-version[Cyface Android SDK Readme]

== In case you need to publish _manually_ to the Github Registry

[arabic]
. Make sure you are authenticated to the repository:
* You need a Github account with write-access to this Github repository
* Create a https://github.com/settings/tokens[personal access token on Github] with "write:packages" permissions
* Copy `gradle.properties.template` to `gradle.properties` and adjust:
+
....
githubUser=YOUR_USERNAME
githubToken=YOUR_ACCESS_TOKEN
....
. Execute the publish command `./gradlew publishAll`


[[license]]
== License

Copyright 2017-2025 Cyface GmbH

This file is part of the Cyface Utils for Android.

The Cyface Utils for Android is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The Cyface Utils for Android is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with the Cyface Utils for Android. If not, see http://www.gnu.org/licenses/.
