# This workflow ensures the building step works
#
# @author Armin Schnabel
# @version 1.0.0
# @since 1.1.4
name: Gradle Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Create empty local.properties which is required
      run: echo "" > local.properties

    - name: Build with Gradle
      run: ./gradlew build