# This workflow ensures the building step works
#
# @author Armin Schnabel
# @version 1.1.1
# @since 1.1.4
name: Gradle Build

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Create gradle.properties which is required
      run: cp gradle.properties.template gradle.properties

    - name: Build with Gradle
      run: ./gradlew build
