# This workflow ensures the building step works
#
# @author Armin Schnabel
# @version 1.1.2
# @since 1.1.4
name: Gradle Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Add gradle.properties
      run: |
        cp gradle.properties.template gradle.properties
        # Disable jdk version setting to as it's defined above
        sed -i "s/org.gradle.java.home=/#org.gradle.java.home=/g" gradle.properties

    - name: Build with Gradle
      run: ./gradlew build
